name = "LSL"
uuid = "57c3d5b1-721f-43a0-b20c-e9152d812276"
authors = ["Samuel Powell"]
version = "0.2.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
liblsl_jll = "b37880e1-55fa-5503-9f1a-f1223ce0b53e"

[compat]
BinaryProvider = "^0.5.6"
CEnum = "^0.2.0"
LightXML = "^0.8.1"
julia = "^1.3.0"
liblsl_jll = "^1.13.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
